version: "3"

services:
  db:
    image: mysql:5.7
    container_name: tbox_database
    logging:
      driver: none
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "tbox"
      MYSQL_USER: "dchlong"
      MYSQL_PASSWORD: "dchlong"
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"